settings = {
    "token": None,
    "debug": False,
    "format_message": "[%timestamp] <%username> | %content %edited",
    "format_newline": "                       %content",
    "format_reply": "[REPLY] <%username> | /--> [%timestamp] %content",
    "format_reactions": "[REACT]                \\--< %reactions",
    "format_one_reaction": "%count:%reaction",
    "format_timestamp": "%H:%M",
    "edited_string": "(edited)",
    "reactions_separator": "; ",
    "limit_username": 10,
    "limit_global_name": 15,
    "convert_timezone": True,
    "format_status_line_l": " %global_name (%username) - %status  %unreads %action %typing",
    "format_status_line_r": None,
    "format_title_line_l": " %server: %channel",
    "format_title_line_r": "%rich",
    "limit_typing_string": 30,
    "format_rich": "playing: %name - %state - %details ",
    "format_prompt": "[%channel] > ",
    "send_typing": True,
    "ack_throttling": 5,
    "use_nick_when_avail": True,
    "tree_width": 30,
    "tree_vert_line": "|",
    "format_title_tree": " endcord",
    "tree_drop_down_vline": "|",
    "tree_drop_down_hline": "-",
    "tree_drop_down_corner": "\\",
    "remember_state": True,
    "reply_mention": True,
    "cache_typed": True,
}
