settings = {
    "token": None,
    "debug": False,
    "limit_chat_buffer": 100,
    "limit_username": 10,
    "limit_global_name": 15,
    "convert_timezone": True,
    "format_message": "[%timestamp] <%username> | %content %edited",
    "format_newline": "                       %content",
    "format_reply": "[REPLY] <%username> | /--> [%timestamp] %content",
    "format_reactions": "[REACT]                \\--< %reactions",
    "format_one_reaction": "%count:%reaction",
    "format_timestamp": "%H:%M",
    "edited_string": "(edited)",
    "reactions_separator": "; ",
    "format_status_line_l": " %global_name (%username) - %status  %unreads %action %typing",
    "format_status_line_r": None,
    "format_title_line_l": " %server: %channel",
    "format_title_line_r": "%rich",
    "limit_typing_string": 30,
    "format_rich": "playing: %name - %state - %details ",
    "format_prompt": "[%channel] > ",
    "send_typing": True,
    "desktop_notifications": True,
    "linux_notification_sound": "message",
    "ack_throttling": 5,
    "use_nick_when_avail": True,
    "tree_width": 30,
    "tree_vert_line": "|",
    "format_title_tree": " endcord  %task",
    "tree_drop_down_vline": "|",
    "tree_drop_down_hline": "-",
    "tree_drop_down_corner": "\\",
    "remember_state": True,
    "reply_mention": True,
    "cache_typed": True,
    "cursor_on_time": 0.7,
    "cursor_off_time": 0.5,
    "blocked_mode": 1,
    "hide_spam": True,
    "color_format_default": [-1, -1],
    "color_format_mention": [209, 234],
    "color_format_blocked": [242, -1],
    "color_tree_default": [255, -1],
    "color_tree_selected": [233, 255],
    "color_tree_muted": [242, -1],
    "color_tree_active": [255, 234],
    "color_tree_unseen": [-1, -1],
    "color_tree_mentioned": [197, -1],
    "color_tree_active_mentioned": [197, 234],
}
